# fly.toml app configuration file generated for noats on 2025-07-19T17:16:38-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "noats" 
primary_region = "gru"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[[http_service.checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/health" # Verifique se você tem essa rota no seu app Python
    protocol = "http"

# Se você estiver usando um volume para o banco de dados, adicione esta seção
# [mounts]
#   source = "noats_data"
#   destination = "/data"